print("Hello \"beautiful\" world")
print('I\'m Sagar Kumar')
print("line A\nline B\nline C")
print("Sagar\tKumar")  
print("this is backslash\\")
print("this is double backslash\\\\")
print("hell\blo")